-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE habit (
    id SERIAL PRIMARY KEY,
    name character varying(30) NOT NULL,
    description character varying(60) NOT NULL,
    last_completed timestamp without time zone NOT NULL DEFAULT '1999-01-01 00:00:00'::timestamp without time zone,
    streak integer DEFAULT 0
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX habit_pkey ON habit(id int4_ops);
